{
    "name":"MainMenu",
    "displayName":"主菜单",
    "customData":null,
    "items":[
        {
            "name":"work",
            "icon":"desktop",
            "displayName":"工作台",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"MyWorks",
                    "icon":null,
                    "displayName":"我的工作",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/myJob"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"permission",
            "icon":"key",
            "displayName":"权限管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"UserManagement",
                    "icon":null,
                    "displayName":"用户管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/userManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"RoleManagement",
                    "icon":null,
                    "displayName":"角色管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/roleManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"CheckManagement",
            "icon":"api",
            "displayName":"入住管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"orgType",
                    "icon":null,
                    "displayName":"机构类型管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/orgTypeManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"orgManager",
                    "icon":null,
                    "displayName":"机构管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/orgManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"SiteManagement",
            "icon":"flag",
            "displayName":"站点管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"ContentManagement",
                    "icon":null,
                    "displayName":"内容管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"ChannelManagel",
                    "icon":null,
                    "displayName":"栏目管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"StyleManagement",
                    "icon":null,
                    "displayName":"模板管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"Greater",
                    "icon":null,
                    "displayName":"一键生成",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"ReportCenter",
            "icon":"notification",
            "displayName":"报表中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"jyreport",
                    "icon":null,
                    "displayName":"经营报表",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/jyreport"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"gjReport",
                    "icon":null,
                    "displayName":"供给报表",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/gjreport"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"MessageCenter",
            "icon":"notification",
            "displayName":"消息中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"myMessage",
                    "icon":null,
                    "displayName":"我的消息",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"userSetting",
            "icon":"schedule",
            "displayName":"个人设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"accountSafe",
                    "icon":null,
                    "displayName":"账号安全",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"systemSetting",
            "icon":"setting",
            "displayName":"系统设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"logManager",
                    "icon":null,
                    "displayName":"操作日志",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        }
    ]
}