{
    "name":"MainMenu",
    "displayName":"主菜单",
    "customData":null,
    "items":[
        {
            "name":"work",
            "icon":"desktop",
            "displayName":"工作台",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"MyWorks",
                    "icon":null,
                    "displayName":"我的工作",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/myJob"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"course",
            "icon":"book",
            "displayName":"课程需求",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"course",
                    "icon":null,
                    "displayName":"课程需求",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"liveClassManager",
            "icon":"video-camera",
            "displayName":"直播课管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"liveClassCreate",
                    "icon":null,
                    "displayName":"新建直播课",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"liveClassManager",
                    "icon":null,
                    "displayName":"直播课管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"demandManager",
            "icon":"laptop",
            "displayName":"点播课管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"demandCreate",
                    "icon":null,
                    "displayName":"新建点播课",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"demandManager",
                    "icon":null,
                    "displayName":"点播课管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"openClassManager",
            "icon":"scan",
            "displayName":"公开课管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"openClassCreate",
                    "icon":null,
                    "displayName":"新建公开课",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"openClassManager",
                    "icon":null,
                    "displayName":"公开课管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"resourceManager",
            "icon":"database",
            "displayName":"资源管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"fileManager",
                    "icon":null,
                    "displayName":"附件管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"coursewareManager",
                    "icon":null,
                    "displayName":"课件管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"questionsManager",
            "icon":"file-text",
            "displayName":"试题管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"questionCreate",
                    "icon":null,
                    "displayName":"新建试题",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"questionsManager",
                    "icon":null,
                    "displayName":"试题管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"paperManager",
            "icon":"copy",
            "displayName":"试卷管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"paperCreate",
                    "icon":null,
                    "displayName":"新建试卷",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"paperManager",
                    "icon":null,
                    "displayName":"试卷管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"examManager",
            "icon":"code-o",
            "displayName":"考试管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"examList",
                    "icon":null,
                    "displayName":"考试列表",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"scoreManager",
                    "icon":null,
                    "displayName":"成绩管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"MessageCenter",
            "icon":"notification",
            "displayName":"消息中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"myMessage",
                    "icon":null,
                    "displayName":"我的消息",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"userSetting",
            "icon":"schedule",
            "displayName":"个人设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"accountSafe",
                    "icon":null,
                    "displayName":"账号安全",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"systemSetting",
            "icon":"setting",
            "displayName":"系统设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"logManager",
                    "icon":null,
                    "displayName":"操作日志",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        }
    ]
}
