{
    "name":"MainMenu",
    "displayName":"主菜单",
        "customData":"positionEnterprise.png",
    "items":[
        {
            "name":"work",
            "icon":"desktop",
            "displayName":"工作台",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"MyWorks",
                    "icon":null,
                    "displayName":"我的工作",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/myJob"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"permission",
            "icon":"key",
            "displayName":"权限管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"UserManagement",
                    "icon":null,
                    "displayName":"用户管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/userManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"RoleManagement",
                    "icon":null,
                    "displayName":"角色管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/roleManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"settleManager",
            "icon":"api",
            "displayName":"入驻管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"InterviewerManager",
                    "icon":null,
                    "displayName":"面试官管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/faceViewerManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
       
        {
            "name":"jobManager",
            "icon":"idcard",
            "displayName":"应聘管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"jobManager",
                    "icon":null,
                    "displayName":"应聘管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
              
                {
                    "name":"enterManager",
                    "icon":null,
                    "displayName":"录用列表",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"MessageCenter",
            "icon":"notification",
            "displayName":"消息中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"myMessage",
                    "icon":null,
                    "displayName":"我的消息",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"userSetting",
            "icon":"schedule",
            "displayName":"个人设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"accountSafe",
                    "icon":null,
                    "displayName":"账号安全",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"systemSetting",
            "icon":"setting",
            "displayName":"系统设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"logManager",
                    "icon":null,
                    "displayName":"操作日志",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        }
    ]
}