{
    "name":"MainMenu",
    "displayName":"主菜单",
    "customData":null,
    "items":[
        {
            "name":"work",
            "icon":"desktop",
            "displayName":"工作台",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"MyWorks",
                    "icon":null,
                    "displayName":"我的工作",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/myJob"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"permission",
            "icon":"key",
            "displayName":"权限管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"UserManagement",
                    "icon":null,
                    "displayName":"用户管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/userManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"RoleManagement",
                    "icon":null,
                    "displayName":"角色管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/roleManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"CheckManagement",
            "icon":"api",
            "displayName":"入驻管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"facultyManager",
                    "icon":null,
                    "displayName":"院系管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/study/departmentManagement"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"trainingEnterpriseManager",
                    "icon":null,
                    "displayName":"培训企业管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/study/enterpriseManagement"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"govManager",
                    "icon":null,
                    "displayName":"政府管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/gorvermentManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"projectDemandEnterpriseManager",
                    "icon":null,
                    "displayName":"项目需求企业管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/enterpriseManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"intermediaryManager",
                    "icon":null,
                    "displayName":"中介管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/intermediaryManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"jobDemandEnterpriseManager",
                    "icon":null,
                    "displayName":"职位需求企业管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/enterpriseMange"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"serviceManager",
            "icon":"appstore",
            "displayName":"服务管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"dockingCenterStudy",
                    "icon":null,
                    "displayName":"学习对接中心",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/study/relationCenterManagement"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"dockingCenterDemand",
                    "icon":null,
                    "displayName":"项目对接中心",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/relationCenterManagement"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"dockingCenterPosition",
                    "icon":null,
                    "displayName":"职位对接中心",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/relationCenterManagement"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"SiteManagement",
            "icon":"flag",
            "displayName":"站点管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"ContentManagement",
                    "icon":null,
                    "displayName":"内容管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"ChannelManagel",
                    "icon":null,
                    "displayName":"栏目管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"StyleManagement",
                    "icon":null,
                    "displayName":"模板管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"Greater",
                    "icon":null,
                    "displayName":"一键生成",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"MessageCenter",
            "icon":"notification",
            "displayName":"消息中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"myMessage",
                    "icon":null,
                    "displayName":"我的消息",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"userSetting",
            "icon":"schedule",
            "displayName":"个人设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"accountSafe",
                    "icon":null,
                    "displayName":"账号安全",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"systemSetting",
            "icon":"setting",
            "displayName":"系统设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"logManager",
                    "icon":null,
                    "displayName":"操作日志",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        }
    ]
}