{
    "name":"MainMenu",
    "displayName":"主菜单",
    "customData":null,
    "items":[
        {
            "name":"work",
            "icon":"desktop",
            "displayName":"工作台",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"MyWorks",
                    "icon":null,
                    "displayName":"我的工作",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/myJob"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"permission",
            "icon":"key",
            "displayName":"权限管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"UserManagement",
                    "icon":null,
                    "displayName":"用户管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/userManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"RoleManagement",
                    "icon":null,
                    "displayName":"角色管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/careerLink/roleManage"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"checkInManager",
            "icon":"api",
            "displayName":"入驻管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"enterpriseStaffs",
                    "icon":null,
                    "displayName":"员工管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/staff"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"projectManager",
            "icon":"appstore-o",
            "displayName":"项目管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"needManager",
                    "icon":null,
                    "displayName":"需求管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/D/demandList"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"demandProjectManager",
                    "icon":null,
                    "displayName":"项目管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/D/projectList"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name":"contractManager",
                    "icon":null,
                    "displayName":"合同管理",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/demand/D/compactList"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"meetingManager",
            "icon":"hourglass",
            "displayName":"会议管理",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"meetingList",
                    "icon":null,
                    "displayName":"会议列表",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                },
                {
                    "name": "netMeetProjectList",
                    "icon": null,
                    "displayName": "网洽会项目列表",
                    "order": 0,
                    "url": null,
                    "customData": [
                        {
                            "path":"/demand/D/netMeetProjectList"
                        }
                    ],
                    "target": null,
                    "isEnabled": true,
                    "isVisible": true,
                    "items": []
                },
                {
                    "name": "netMeetCompactList",
                    "icon": null,
                    "displayName": "网洽会合同列表",
                    "order": 0,
                    "url": null,
                    "customData": [
                        {
                            "path":"/demand/D/netMeetCompactList"
                        }
                    ],
                    "target": null,
                    "isEnabled": true,
                    "isVisible": true,
                    "items": []
                },
            ]
        },
        {
            "name":"MessageCenter",
            "icon":"notification",
            "displayName":"消息中心",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"myMessage",
                    "icon":null,
                    "displayName":"我的消息",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"userSetting",
            "icon":"schedule",
            "displayName":"个人设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"accountSafe",
                    "icon":null,
                    "displayName":"账号安全",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        },
        {
            "name":"systemSetting",
            "icon":"setting",
            "displayName":"系统设置",
            "order":0,
            "url":null,
            "customData":null,
            "target":null,
            "isEnabled":true,
            "isVisible":true,
            "items":[
                {
                    "name":"logManager",
                    "icon":null,
                    "displayName":"操作日志",
                    "order":0,
                    "url":null,
                    "customData":[
                        {
                            "path":"/Exception"
                        }
                    ],
                    "target":null,
                    "isEnabled":true,
                    "isVisible":true,
                    "items":[

                    ]
                }
            ]
        }
    ]
}